#!/usr/bin/env bash
# Dotfiles deployment script using GNU stow
# Symlinks dotfiles from arch-config/dotfiles to home directory
# Safe to run multiple times (idempotent)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
DOTFILES_DIR="$REPO_ROOT/dotfiles"
HOME_DIR="${HOME}"

log() {
    echo "[dotfiles-deploy] $*"
}

error() {
    echo "[dotfiles-deploy] ERROR: $*" >&2
    exit 1
}

# Check if dotfiles directory exists
if [ ! -d "$DOTFILES_DIR" ]; then
    log "Dotfiles directory not found at $DOTFILES_DIR, skipping"
    exit 0
fi

log "Starting dotfiles deployment..."

# Backup existing dotfiles if they're not symlinks
backup_if_exists() {
    local file="$1"
    if [ -e "$HOME_DIR/$file" ] && [ ! -L "$HOME_DIR/$file" ]; then
        local backup_dir="$HOME_DIR/.dotfiles-backup-$(date +%Y%m%d-%H%M%S)"
        mkdir -p "$backup_dir"
        log "Backing up existing $file to $backup_dir"
        rsync -a --relative "$HOME_DIR/$file" "$backup_dir/"
    fi
}

# Critical dotfiles to backup before deployment
CRITICAL_FILES=(
    ".config/X11"
    ".config/picom"
    ".config/rofi"
    ".config/nvim"
    ".config/alacritty"
    ".config/tmux"
    ".config/autorandr"
    ".config/darkman"
    ".dwm"
    ".zshrc"
    ".bashrc"
    ".bash_profile"
    ".aliases"
    ".gitconfig"
    ".local/bin"
    ".local/share/applications"
)

# Clean up old symlinks that point to wrong location (e.g., ~/dotfiles instead of ~/.config/arch-config/dotfiles)
log "Cleaning up old symlinks pointing to ~/dotfiles..."
find "$HOME_DIR" -maxdepth 1 -type l 2>/dev/null | while read link; do
    target=$(readlink "$link" 2>/dev/null || true)
    # Remove if symlink target looks like old path: starts with "dotfiles/" (relative path)
    if [ -n "$target" ] && echo "$target" | grep -q "^dotfiles/"; then
        log "Removing old symlink: $(basename "$link") → $target"
        rm -f "$link"
    fi
done

# Also clean up .config / .local symlinks that still point at the retired
# standalone ~/dotfiles checkout (target has "dotfiles/" but not
# "arch-config/dotfiles/"). Nothing else is touched — app runtime symlinks
# like Chromium's SingletonLock must be left alone.
for base in "$HOME_DIR/.config" "$HOME_DIR/.local"; do
    find "$base" -maxdepth 3 -type l 2>/dev/null | while read -r link; do
        target=$(readlink "$link" 2>/dev/null || true)
        case "$target" in
            *arch-config/dotfiles/*) : ;;
            */dotfiles/*|dotfiles/*)
                log "Removing stale ~/dotfiles symlink: $link → $target"
                rm -f "$link" ;;
        esac
    done
done

# Deploy with stow
log "Deploying dotfiles with GNU stow..."
cd "$DOTFILES_DIR"

# Use stow with --verbose to show what's being done
# --target: Where to create symlinks (home directory)
# . : Everything in current directory
if ! stow --verbose=1 --target="$HOME_DIR" .; then
    error "Stow failed. Check for conflicts with existing files."
fi

# ~/.local/{bin,share/applications} are stow-ignored (they mix tracked files
# with entries generated by Chrome/JetBrains/etc). Link the tracked files in
# individually so those dirs stay real and writable.
link_tracked_files() {
    local rel="$1"                     # e.g. .local/share/applications
    local src="$DOTFILES_DIR/$rel"
    local dst="$HOME_DIR/$rel"
    [ -d "$src" ] || return 0
    mkdir -p "$dst"
    ( cd "$src" && find . -mindepth 1 \( -type f -o -type l \) -printf '%P\n' ) | while read -r f; do
        mkdir -p "$dst/$(dirname "$f")"
        if [ -L "$dst/$f" ] || [ ! -e "$dst/$f" ]; then
            ln -sfn "$src/$f" "$dst/$f"
        else
            log "skip $rel/$f (real file exists)"
        fi
    done
}
log "Linking tracked ~/.local files..."
link_tracked_files ".local/bin"
link_tracked_files ".local/share/applications"

# ~/.xinitrc: a bare `startx` (e.g. bash login shell, or run by hand) only
# reads ~/.xinitrc. Point it at the real session script so dwm comes up no
# matter which shell or invocation started X.
if [ -L "$HOME_DIR/.xinitrc" ] || [ ! -e "$HOME_DIR/.xinitrc" ]; then
    ln -sfn "$HOME_DIR/.config/X11/xinitrc" "$HOME_DIR/.xinitrc"
    log "Linked ~/.xinitrc -> ~/.config/X11/xinitrc"
fi

# Login shell should be zsh (the dwm-launch logic lives in ~/.zprofile).
ZSH_BIN="$(command -v zsh || true)"
if [ -n "$ZSH_BIN" ] && [ "$(getent passwd "$USER" | cut -d: -f7)" != "$ZSH_BIN" ]; then
    log "Setting login shell to $ZSH_BIN"
    grep -qxF "$ZSH_BIN" /etc/shells || echo "$ZSH_BIN" | sudo tee -a /etc/shells >/dev/null
    sudo chsh -s "$ZSH_BIN" "$USER" || log "chsh failed (set login shell to zsh manually)"
fi

# nvm: dev Node is managed per-project via nvm (~/.zsh-config/nvm.zsh auto-switches
# on .nvmrc). Not a pacman package — install upstream into ~/.nvm if missing.
# PROFILE=/dev/null keeps the installer from editing .bashrc/.zshrc (the loader
# lines are already tracked). ~/.npmrc must stay free of a `prefix`/`globalconfig`
# setting — nvm refuses to load otherwise.
NVM_VERSION="v0.40.7"
if [ ! -s "$HOME_DIR/.nvm/nvm.sh" ]; then
    log "Installing nvm $NVM_VERSION -> ~/.nvm"
    PROFILE=/dev/null bash -c \
      "curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash" \
      >/dev/null 2>&1 || log "nvm install failed (network?) — install manually"
fi
if [ -s "$HOME_DIR/.nvm/nvm.sh" ]; then
    # shellcheck disable=SC1091
    export NVM_DIR="$HOME_DIR/.nvm"; . "$NVM_DIR/nvm.sh"
    nvm which default >/dev/null 2>&1 || {
        log "Installing default Node (latest LTS) via nvm"
        nvm install --lts >/dev/null 2>&1 && nvm alias default 'lts/*' >/dev/null 2>&1
    }

    # safe-chain (npm/npx/pip/... malware guard). Installed into ~/.npm-global
    # with an explicit --prefix so it survives `nvm use` (nvm's own global dir is
    # per-Node-version). The shell loaders are already tracked (.bashrc/.zshrc
    # source ~/.safe-chain/scripts/init-posix.sh via a guarded line).
    # One-time manual step on a fresh box: `safe-chain setup` (generates
    # ~/.safe-chain/{scripts,certs}), then delete the raw `source …init-posix.sh`
    # lines it appends to ~/.bashrc and ~/.zshrc.
    if command -v npm >/dev/null 2>&1 && [ ! -x "$HOME_DIR/.npm-global/bin/safe-chain" ]; then
        log "Installing @aikidosec/safe-chain -> ~/.npm-global"
        npm install -g --prefix "$HOME_DIR/.npm-global" @aikidosec/safe-chain >/dev/null 2>&1 \
          || log "safe-chain install failed — run: npm i -g --prefix ~/.npm-global @aikidosec/safe-chain && safe-chain setup"
    fi
fi

# tmux plugins (tmux.conf uses tpm + a plugin list). tpm and the plugins are
# not vendored — bootstrap them so tmux looks the same on every machine.
if grep -q "@plugin" "$HOME_DIR/.config/tmux/tmux.conf" 2>/dev/null; then
    TPM_DIR="$HOME_DIR/.config/tmux/plugins/tpm"
    [ -d "$TPM_DIR/.git" ] || git clone -q https://github.com/tmux-plugins/tpm "$TPM_DIR" \
        && log "tpm installed"
    # tmux.conf sources '~/.tmux/plugins/tpm/tpm'
    mkdir -p "$HOME_DIR/.tmux"
    [ -e "$HOME_DIR/.tmux/plugins" ] || ln -sfn "$HOME_DIR/.config/tmux/plugins" "$HOME_DIR/.tmux/plugins"
    if [ -x "$TPM_DIR/scripts/install_plugins.sh" ]; then
        TERM=${TERM:-xterm-256color} tmux -L dotfiles-deploy -f "$HOME_DIR/.config/tmux/tmux.conf" new-session -d 2>/dev/null || true
        "$TPM_DIR/scripts/install_plugins.sh" >/dev/null 2>&1 || log "tmux plugin install had issues (run 'prefix + I' in tmux)"
        tmux -L dotfiles-deploy kill-server 2>/dev/null || true
        log "tmux plugins installed"
    fi
fi

log "Dotfiles deployed successfully"

# Run systemd service configuration if available
if [ -f "$REPO_ROOT/scripts/dotfiles-systemd.sh" ]; then
    log "Configuring systemd user services..."
    bash "$REPO_ROOT/scripts/dotfiles-systemd.sh"
fi

log "Dotfiles deployment complete"
